// Auto-generated by scripts/deploy-to-bio.sh — do not edit by hand.
// Sets the proxy API base for the unlisted GitHub Pages deployment. The client
// calls ${window.ETHICA_API_BASE}/api/* cross-origin; all such calls carry a
// ngrok-skip-browser-warning header (see client/src/llm.js + save-sync.js).
//
// NOTE: the value below is Cameron's CURRENT ngrok tunnel URL, which is
// EPHEMERAL and changes when ngrok restarts. Once he claims his free static
// ngrok domain at dashboard.ngrok.com, re-run with:
//   API_BASE="https://<static>.ngrok-free.app" ./scripts/deploy-to-bio.sh
// and set DOMAIN in proxy/launch.sh so the tunnel comes up on that domain.
window.ETHICA_API_BASE = 'https://49f7-96-87-223-194.ngrok-free.app';
